Migrate build and setup from setup.py to pyproject.toml
andrew-d/python-multipart pull request #52
Opened 2022-11-03 16:04 UTC by axelfauvel

As discussed in https://github.com/andrew-d/python-multipart/issues/37

Here is the first part towards automating the release process. You can now run the following code to build the package :

```bash
pip install --upgrade build
python -m build
```

This will generate both `.whl` and `.tar.gz` files, last step will be to publish them to pypi using twine.

What is in this PR ?
* Move dependencies setup from `requirements.txt` & `setup.py` to `pyproject.toml`
* Extract `__version__` from package to `pyproject.toml`
* Move doc dependencies to pyproject.toml

2022-11-03 16:12 UTC, Ambro17 commented on multipart/_version.py
> +import pkg_resources
Should we use the newer [importlib.metadata](https://docs.python.org/3/library/importlib.metadata.html#module-importlib.metadata) instead?

2022-11-03 16:14 UTC, Ambro17 commented on pyproject.toml
> +requires = ["setuptools", "setuptools-scm"]
I wouldn't choose setuptools as the build backend as it has to support many legacy workflows that prevent innovations in other tools. I would propose `hatchling.build` as the official tutorial does https://packaging.python.org/en/latest/tutorials/packaging-projects/#creating-pyproject-toml (although implicitly as listing it as the first choice)

2022-11-03 16:14 UTC, Ambro17 commented on pyproject.toml
> +version = "0.0.5"
Should we bump to 0.0.6?

2022-11-03 16:16 UTC, Ambro17 commented on pyproject.toml
> +    "atomicwrites==1.2.1",
Dependencies should not be hard pinned here as it forces ALL users of this lib to use SPECIFICALLY this version. More relaxed requirements as `atomicwrites>=1.0.0` are prefered. The minimum version that works, the better, that allows users more freedom to pin in their apps without a dependency (that's even transitive in the case of fastapi users) forcing you to certain version that might have a security vuln for example

2022-11-03 16:17 UTC, Ambro17 commented on pyproject.toml
> +dev = [
If we were to pin, here would be better as it will only be done if we're setting up a dev enviornment, not a library usage environment

2022-11-03 16:29 UTC, axelfauvel commented
Thanks for the review Nahuel, I'll work on it tomorrow

2022-11-03 16:44 UTC, Kludex requested changes
Can we try to match the build setup that [`starlette`](https://github.com/encode/starlette) has?

2022-11-18 01:06 UTC, Ambro17 commented
Hi, let me know if you need some help. If you don't have time i can update the or too with @Kludex  suggestion

2023-02-07 07:12 UTC, Kludex commented
@Ambro17 do you take care of this or should I?

2023-02-07 13:02 UTC, Kludex commented
Ah, this was already done.

2023-02-07 13:02 UTC, closed without merging